default:
  image: node:latest
  before_script:
    - npm ci --cache .npm --prefer-offline
    - echo "//registry.npmjs.org/:_authToken=AUTH_TOKEN" | tee -a .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - publish

publish_npm:
  stage: publish
  image: node
  script:
    - npm run release
    - npm publish
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: never
    - changes:
        - package.json
        - package-lock.json
        - src/**/*
        - .gitlab-ci.yml