name: Publish NPM Package

on:
  push:
    branches:
      - "**"
    paths:
      - package.json
      - package-lock.json
      - src/js/**
      - src/scss/**
      - .github/workflows/publish.yml

jobs:
  publish:
    # if: github.ref != 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            .npm
          key: ${{ runner.os }}-npm-${{ github.ref_name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ github.ref_name }}-
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Run release
        run: npm run release

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}